-- The local backend applies versioned PostgreSQL schema files from ./migrations on startup.
-- Use npm run db:migrate to apply them manually. This file replaces the old Supabase-era setup script,
-- which dropped tables before recreating them, with a safe pointer to the versioned migrations.
