-- PostgreSQL Database Schema for Fiona EMR Project
-- Copy and run this script in your Supabase SQL Editor.

-- Drop existing tables if they exist (clean setup)
DROP TABLE IF EXISTS visit_logs CASCADE;
DROP TABLE IF EXISTS medication_orders CASCADE;
DROP TABLE IF EXISTS soap_notes CASCADE;
DROP TABLE IF EXISTS vitals CASCADE;
DROP TABLE IF EXISTS immunizations CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;


-- 1. Patients Table
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    section TEXT,
    age INT,
    gender TEXT,
    status TEXT DEFAULT 'Active',
    status_color TEXT DEFAULT 'green',
    date_of_birth DATE,
    grade_level TEXT,
    allergies TEXT DEFAULT 'None',
    chronic_conditions TEXT DEFAULT 'None',
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relationship TEXT,
    graduation_year INT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Adjust start point for IDs to simulate existing records
ALTER TABLE patients ALTER COLUMN id RESTART WITH 1000;

-- 2. Vitals Table
CREATE TABLE vitals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    temperature NUMERIC(4, 1),
    heart_rate INT,
    blood_pressure TEXT,
    o2_sat INT,
    respiratory_rate INT,
    recorded_at TIMESTAMPTZ DEFAULT now()
);

-- 3. SOAP Notes Table
CREATE TABLE soap_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    subjective TEXT,
    objective TEXT,
    assessment TEXT,
    plan TEXT,
    disposition TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Medication Orders Table
CREATE TABLE medication_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    medication TEXT NOT NULL,
    dosage TEXT NOT NULL, -- Will store "${strength} ${form}" for backward compatibility
    strength TEXT,
    form TEXT,
    route TEXT NOT NULL,
    administered_by TEXT,
    consent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Visit Logs (Activity Feed / Audit Log)
CREATE TABLE visit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'Check-in', 'Vitals Recorded', 'Clinical Note Added', 'Medication Ordered', 'Record Viewed'
    details TEXT,
    performed_by TEXT NOT NULL DEFAULT 'System',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Accounts Table (Staff / Physicians)
CREATE TABLE accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- SHA-256 hash
    role TEXT DEFAULT 'physician',
    mfa_enabled BOOLEAN DEFAULT FALSE,
    mfa_type TEXT DEFAULT 'none', -- 'none', 'totp', 'email'
    mfa_secret TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Immunization Matrix Table
CREATE TABLE immunizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    vaccine_name TEXT NOT NULL,
    doses_received INT DEFAULT 0,
    doses_required INT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Parental Consents Table
CREATE TABLE parental_consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    consent_type TEXT NOT NULL,
    document_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    date_granted DATE NOT NULL DEFAULT CURRENT_DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 9. Excuse Slips Table
CREATE TABLE excuse_slips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    excuse_reason TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    teacher_notified TEXT,
    verification_hash TEXT UNIQUE NOT NULL,
    created_by TEXT NOT NULL DEFAULT 'System',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Seed Account (Password: password123)
INSERT INTO accounts (name, email, password, role)
VALUES 
('Developer Tester', 'dev@fiona.com', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'physician');

-- Disable Row Level Security (RLS) for all tables to allow development API access
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE vitals DISABLE ROW LEVEL SECURITY;
ALTER TABLE soap_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE medication_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE visit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE immunizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE parental_consents DISABLE ROW LEVEL SECURITY;
ALTER TABLE excuse_slips DISABLE ROW LEVEL SECURITY;


