CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    section TEXT,
    age INT,
    gender TEXT,
    status TEXT DEFAULT 'Checked Out',
    status_color TEXT DEFAULT 'gray',
    date_of_birth DATE,
    grade_level TEXT,
    allergies TEXT DEFAULT 'None',
    chronic_conditions TEXT DEFAULT 'None',
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relationship TEXT,
    parent_email TEXT,
    adviser_name TEXT,
    adviser_email TEXT,
    graduation_year INT,
    created_at TIMESTAMPTZ DEFAULT now()
);

SELECT setval(
    pg_get_serial_sequence('patients', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM patients), 999), 999),
    true
);

CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'physician',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vitals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    temperature NUMERIC(4, 1),
    heart_rate INT,
    blood_pressure TEXT,
    o2_sat INT,
    respiratory_rate INT,
    recorded_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS soap_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    subjective TEXT,
    objective TEXT,
    assessment TEXT,
    plan TEXT,
    disposition TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS medication_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    medication TEXT NOT NULL,
    dosage TEXT NOT NULL,
    strength TEXT,
    form TEXT,
    route TEXT NOT NULL,
    administered_by TEXT,
    consent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS visit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    details TEXT,
    performed_by TEXT NOT NULL DEFAULT 'System',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS immunizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    vaccine_name TEXT NOT NULL,
    doses_received INT DEFAULT 0,
    doses_required INT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parental_consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    consent_type TEXT NOT NULL,
    document_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    date_granted DATE NOT NULL DEFAULT CURRENT_DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS excuse_slips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    excuse_reason TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    teacher_notified TEXT,
    verification_hash TEXT UNIQUE NOT NULL,
    created_by TEXT NOT NULL DEFAULT 'System',
    principal_acknowledged BOOLEAN DEFAULT FALSE,
    principal_acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS incident_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    incident_details TEXT NOT NULL,
    adviser_name TEXT,
    adviser_status TEXT DEFAULT 'Pending',
    adviser_confirmed_at TIMESTAMPTZ,
    parent_name TEXT,
    parent_status TEXT DEFAULT 'Pending',
    parent_confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    recipient_type TEXT NOT NULL,
    recipient_email TEXT NOT NULL,
    subject TEXT,
    body TEXT,
    sent_at TIMESTAMPTZ DEFAULT now(),
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMPTZ,
    response_status TEXT
);

CREATE TABLE IF NOT EXISTS clinic_settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE INDEX IF NOT EXISTS idx_vitals_patient_id ON vitals(patient_id);
CREATE INDEX IF NOT EXISTS idx_soap_notes_patient_id ON soap_notes(patient_id);
CREATE INDEX IF NOT EXISTS idx_medication_orders_patient_id ON medication_orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_visit_logs_patient_id ON visit_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_immunizations_patient_id ON immunizations(patient_id);
CREATE INDEX IF NOT EXISTS idx_parental_consents_patient_id ON parental_consents(patient_id);
CREATE INDEX IF NOT EXISTS idx_excuse_slips_patient_id ON excuse_slips(patient_id);
CREATE INDEX IF NOT EXISTS idx_incident_alerts_patient_id ON incident_alerts(patient_id);
CREATE INDEX IF NOT EXISTS idx_email_alerts_patient_id ON email_alerts(patient_id);
CREATE INDEX IF NOT EXISTS idx_patients_status ON patients(status);
CREATE INDEX IF NOT EXISTS idx_patients_name ON patients(name);
CREATE INDEX IF NOT EXISTS idx_visit_logs_created_at ON visit_logs(created_at DESC);

INSERT INTO clinic_settings (key, value) VALUES
    ('principal_email', 'principal@aerohealth.com'),
    ('security_guard_email', 'guard@aerohealth.com'),
    ('school_logo_url', '')
ON CONFLICT (key) DO NOTHING;
