ALTER TABLE accounts
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash TEXT PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_account_id ON auth_sessions(account_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at);

CREATE TABLE IF NOT EXISTS auth_login_attempts (
  email TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  window_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_until TIMESTAMPTZ,
  PRIMARY KEY (email, ip_address)
);

CREATE TABLE IF NOT EXISTS security_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id UUID REFERENCES accounts(id) ON DELETE SET NULL,
  request_method TEXT NOT NULL,
  resource TEXT NOT NULL,
  client_ip TEXT,
  result TEXT NOT NULL DEFAULT 'success',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_security_audit_account_created ON security_audit_events(account_id, created_at DESC);

UPDATE accounts
SET is_active = FALSE
WHERE email IN (
  'dev@aerohealth.com',
  'doctor@aerohealth.com',
  'nurse@aerohealth.com',
  'teacher@aerohealth.com',
  'counselor@aerohealth.com',
  'admin@aerohealth.com'
);
